---
title: "Results for knibe84"
---

```{r setup, include = FALSE}
library("dovetail") 
# Note: added in to evaluate dovetail chunks
```


# Challenge: Simple Nested

Please write your answers for the simple nested challenge below

## HTML `<div>`

<div class='challenge'>

## Challenge

Use the `paste()` function to concatenate the strings "hello" and "there" in R

<div class='solution'>

## Solution

```r
paste("hello", "there")
```

```output
[1] "hello there"
```

</div>
</div>


## {dovetail}

```{challenge}
#' ## Challenge
#' 
#' Use the `paste()` function to concatenate the strings "hello" and "there"
#' in R
#'
#' @solution Solution
#' ```r
paste("hello", "there")
#' ```
#' 
#' ```output
[1] "hello there"
#' ```
```

## pandoc fenced div
::: challenge

## Challenge

Use the `paste()` function to concatenate the strings "hello" and "there" in R

::::: solution

## Solution

```r
paste("hello", "there")
```

```output
[1] "hello there"
```

:::::
:::



--------------------------------------------------------------------------------


# Challenge: Complex Nested

Please write your answers for the complex nested challenge below


## HTML `<div>`

<div class='challenge'>

## Challenge

Use the `paste()` function to concatenate the strings "hello" and "there" in R

<div class='solution'>

## School Solution

```r
paste("hello", "there")
```

```output
[1] "hello there"
```
</div>

Great! Now use `paste0()` to paste together "mono" and "rail" to make
"monorail"

<div class='solution'>

## Fast Solution

```r
paste0("mono", "rail")
```

```output
[1] "monorail"
```

</div>
</div>


## {dovetail}

```{challenge}
#'
#' ## Challenge
#' Use the `paste()` function to concatenate the strings "hello" and "there"
#' in R
#'
#' @solution School Solution
#' 
#' ```r
paste("hello", "there")
#' ```
#'
#' ```output
[1] "hello there"
#' ```
#'
#' @end
#' 
#' Great! Now use `paste0()` to paste together "mono" and "rail"
#' to make "monorail"
#' 
#' @solution Fast Solution
#' 
#' ```r
paste0("mono", "rail")
#' ```
#'
#' ```output
[1] "monorail"
#' ```
```

## pandoc fenced div

::: challenge

## Challenge

Use the `paste()` function to concatenate the strings "hello" and "world" in R

::::: solution

## Solution

```r
paste("hello", "there")
```

```output
[1] "hello there"
```

:::::

Great! Now use 'paste0()' to paste together "mono" and "rail" to make
"monorail"

::::: solution

## Fast Solution

```r
paste0("mono", "rail")
```

```output
[1] "monorail"
```

:::::
:::
